#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'
#
spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'
#  datasource:
#    url:  jdbc:postgresql://localhost:5433/ead-course-v2
#    username: postgres
#    password: banco123
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  rabbitmq:
#    addresses: amqps://vpktunhl:wyMuJffCRZNUqAkmGjHTRsilz1NWREYZ@vulture.rmq.cloudamqp.com/vpktunhl
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost